#
# Action: Test Membership
#
# Tests whether a member name is part of an organization.
#
# copied and adapted from https://github.com/hazelcast/hazelcast-tpm/blob/main/membership/action.yaml
#

name: Test Membership
inputs:
  organization-name:
    required: true
  member-name:
    required: true
outputs:
  is-member:
    description: "Whether the member name is a member of the organization"
    value: ${{ steps.test-membership.outputs.is-member }}
runs:
  using: "composite"
  steps:
    - id: test-membership
      shell: bash
      run: |
        gh api "orgs/${{ inputs.organization-name }}/members/${{ inputs.member-name }}"

        echo "is-member=true" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}