name: Coverage Report

inputs:
  GH_TOKEN:
    required: true
  BOOST_VERSION:
    required: true
  THRIFT_VERSION:
    required: true
  RUN_TESTS:
    required: true
  HAZELCAST_ENTERPRISE_KEY:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  HZ_TEST_AWS_INSTANCE_PRIVATE_IP:
    required: true

runs:
  using: composite
  steps:
    - name: Read Config
      shell: bash
      run: cat .github/config.env >> $GITHUB_ENV

    - shell: bash
      run: |
        echo "BUILD_TYPE=Debug" >> ${GITHUB_ENV}

    - name: Install Necessary Packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y net-tools libssl-dev gdb gcovr lcov curl

    - name: Download hazelcast-enterprise-tests.jar
      shell: bash
      run: |
        gh api "/repos/hazelcast/private-test-artifacts/contents/certs.jar?ref=data" -H "Accept: application/vnd.github.raw" > hazelcast-enterprise-${{ env.HZ_VERSION }}-tests.jar
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Install Boost
      shell: bash
      run: |
        sudo ./scripts/install-boost.sh ${{ inputs.BOOST_VERSION }}

    - name: Install Thrift
      shell: bash
      run: |
        sudo ./scripts/install-thrift.sh ${{ inputs.THRIFT_VERSION }}

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}

    - name: Build
      env:
        BUILD_DIR: build
        COVERAGE: ON
        BUILD_TYPE: ${{ env.BUILD_TYPE }}
      shell: bash
      run: |
        ./scripts/build-unix.sh        \
            -DBUILD_SHARED_LIBS=ON     \
            -DWITH_OPENSSL=ON          \
            -DBUILD_TESTS=ON           \
            -DBUILD_EXAMPLES=OFF

    - name: Test
      if: ${{ inputs.run_tests }}
      env:
        BUILD_DIR: build
        HAZELCAST_ENTERPRISE_KEY: ${{ inputs.HAZELCAST_ENTERPRISE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        HZ_TEST_AWS_INSTANCE_PRIVATE_IP: ${{ inputs.HZ_TEST_AWS_INSTANCE_PRIVATE_IP }}
        BUILD_TYPE: ${{ env.BUILD_TYPE }}
      shell: bash
      run: |
        ulimit -c unlimited
        sudo sh -c "echo 'core' > /proc/sys/kernel/core_pattern"
        sudo sh -c "echo '1' > /proc/sys/kernel/core_uses_pid"
        ./scripts/test-unix.sh

    - name: Collect coverage info
      shell: bash
      run: |
        # collect and list coverage info
        lcov --capture --directory . --no-external -o coverage.info \
              --include "`pwd`/hazelcast/*" --exclude "`pwd`/hazelcast/test/*"
        lcov --list coverage.info
        # generate HTML views
        genhtml coverage.info --output-directory=coverage-html-reports

    - name: Upload HTML views as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          coverage.info
          coverage-html-reports
