name: Update project version

inputs:
  NEXT_VERSION:
    required: true

runs:
  using: composite
  steps:
    - name: Update `vcpkg.json`
      shell: bash
      run: |
        cat <<< $(jq --arg ver "${{ inputs.NEXT_VERSION }}" '.version = $ver' vcpkg.json) > vcpkg.json

    - name: Update `CMakeLists.txt`s
      shell: bash
      run: |
        find . -name 'CMakeLists.txt' | \
            xargs perl -0777 -i -pe 's/(project\s*\([^)]*?\bVERSION\s+)\S+/\1$ENV{NEXT_VERSION}/s'
      env:
        NEXT_VERSION: ${{ inputs.NEXT_VERSION }}

    - name: Print accessible environment variables
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        printenv

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: Update_version_to_${{ inputs.NEXT_VERSION }}_run_${{ github.run_id }}
        title: Update version to `${{ inputs.NEXT_VERSION }}` in `${{ github.ref_name }}`
        body: ""
