#
# Workflow: Build&Test PR for Hazelcast organization members
# This workflow builds multiple configurations for MacOS, Windows, Ubuntu i386 and Ubuntu x64
# If all the builds and tests are success, the PR can be merged.
# It also runs code-coverage and upload the result as an artifact.

name: Build&Test PR
on: 

  # automatic on every pull request
  pull_request_target:

jobs:
  get-refs:
    runs-on: ubuntu-latest=
    steps:
      - name: Get Refs
        id: get-refs
        shell: bash
        run: |
          echo "EVENT: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "PR_NUMBER: ${{ inputs.pr_number }}"
            echo "PR_COMMIT: ${{ inputs.pr_commit }}"
            echo "ref=refs/pull/${{ inputs.pr_number }}/merge" >> $GITHUB_OUTPUT
            echo "merged-ref=${{ inputs.pr_commit }}" >> $GITHUB_OUTPUT
          else
            echo "PR_NUMBER: ${{ github.event.pull_request.number }}"
            echo "ref=refs/pull/${{ github.event.pull_request.number }}/merge" >> $GITHUB_OUTPUT
            echo "merged-ref=''" >> $GITHUB_OUTPUT
          fi
          